#!/usr/bin/env python
import os
import argparse
from numpy import array, arange
from scipy.io import FortranFile
import xarray as xr

try:
    import fv3grid as fg
    has_fv3grid = True
except ImportError:
    has_fv3grid = False

def wrap_longitudes(lons):
    return (lons + 180) % 360 - 180

def open_fv3_binary(fname, dtype='f4', res='C384', tile=1):
    """Reads the binary data for FV3-CHEM input generated by prep_chem_sources.
    Parameters
    ----------
    fname : type
        Description of parameter `fname`.
    **kwargs :
        This is the kwargs for the fv3grid. Users can define the res='C384' and
        the tile=1.
        valid values for them are:
        res = 'C768' 'C384' 'C192' 'C96' 'C48'
        tile = 1 2 3 4 5 6
    Returns
    -------
    xaray DataArray
        Description of returned object.
    """
    w = FortranFile(fname)
    a = w.read_reals(dtype=dtype)
    r = int(res[1:])
    s = a.reshape((r, r), order='F')
    if has_fv3grid:
        grid = fg.get_fv3_grid(res=res, tile=tile)
        lons = wrap_longitudes(grid.longitude)
        grid['longitude'] = lons
        name = os.path.basename(fname).split('.dat')[0].split('.bin')[0]
        #name = fname.split('.bin')[0]
        grid[name] = (('x', 'y'), s)
        return grid
    else:
        print(
            'Please install the fv3grid from https://github.com/bbakernoaa/fv3grid'
        )
        print('to gain the full capability of this dataset')
        return xr.DataArray(s, dims=('x', 'y'))
    
def to_prepchem_binary(data, fname='output.bin', dtype='f4'):
    """Writes to binary file for prep_chem_sources.
    Parameters
    ----------
    dset : data array
        Description of parameter `dset`.
    fname : type
        Description of parameter `fname`.
    dtype : type
        Description of parameter `dtype`.
    Returns
    -------
    type
        Description of returned object.
    """
    f = FortranFile(fname, 'w')
    f.write_record(data.astype(dtype))
    f.close()

# def calc_soil_type(clay,sand,silt,bad_val=100.*100.):
#     from numpy import zeros,where
#     stype = zeros(clay.shape)
#     stype[where((silt + clay*1.5 < 15.) & (clay != bad_val))] = 1.  #SAND
#     stype[where((silt + 1.5*clay >= 15.) & (silt + 1.5*clay <30) & (clay != bad_val))] = 2. #Loamy Sand
#     stype[where((clay >= 7.) & (clay < 20) & (sand >52) & (silt + 2* clay >=30) & (clay != bad_val))] = 3. #Sandy Loam (cond 1)
#     stype[where((clay <   7) & (silt < 50) & (silt+2*clay >= 30) & (clay != bad_val))]   = 3      # sandy loam (cond 2)
#     stype[where((silt >= 50) & (clay >= 12) & (clay < 27 ) & (clay != bad_val))] = 4      # silt loam (cond 1)
#     stype[where((silt >= 50) & (silt < 80) & (clay < 12) & (clay != bad_val))] = 4      # silt loam (cond 2)
#     stype[where((silt >= 80) & (clay < 12) & (clay != bad_val))]     = 5      # silt
#     stype[where((clay >= 7 ) & (clay < 27) &(silt >= 28) & (silt < 50) & (sand <= 52) & (clay != bad_val))] = 6      # loam
#     stype[where((clay >= 20) & (clay < 35) & (silt < 28) & (sand > 45) & (clay != bad_val))] = 7      # sandy clay loam
#     stype[where((clay >= 27) & (clay < 40.) & (sand < 20) & (clay != bad_val))] =  8      # silt clay loam
#     stype[where((clay >= 27) & (clay < 40.) & (sand >= 20) & (sand <= 45) & (clay != bad_val))] = 9      # clay loam
#     stype[where((clay >= 35) & (sand > 45) & (clay != bad_val))] = 10     # sandy clay
#     stype[where((clay >= 40) & (silt >= 40) & (clay != bad_val))] = 11     # silty clay
#     stype[where((clay >= 40) & (sand <= 45) & (silt < 40) & (clay != bad_val))] = 12     # clay
#     return stype

def calc_soil_type(clay,sand,silt):
    from numpy import zeros,where
    stype = zeros(clay.shape)
    stype[where((silt + clay*1.5 < 15.) & (clay < 100))] = 1.  #SAND
    stype[where((silt + 1.5*clay >= 15.) & (silt + 1.5*clay <30) & (clay < 100))] = 2. #Loamy Sand
    stype[where((clay >= 7.) & (clay < 20) & (sand >52) & (silt + 2* clay >=30) & (clay <100))] = 3. #Sandy Loam (cond 1)
    stype[where((clay <   7) & (silt < 50) & (silt+2*clay >= 30) & (clay < 100))]   = 3      # sandy loam (cond 2)
    stype[where((silt >= 50) & (clay >= 12) & (clay < 27 ) & (clay < 100))] = 4      # silt loam (cond 1)
    stype[where((silt >= 50) & (silt < 80) & (clay < 12) & (clay < 100))] = 4      # silt loam (cond 2)
    stype[where((silt >= 80) & (clay < 12) & (clay < 100))]     = 5      # silt
    stype[where((clay >= 7 ) & (clay < 27) &(silt >= 28) & (silt < 50) & (sand <= 52) & (clay < 100))] = 6      # loam
    stype[where((clay >= 20) & (clay < 35) & (silt < 28) & (sand > 45) & (clay < 100))] = 7      # sandy clay loam
    stype[where((clay >= 27) & (clay < 40.) & (sand < 20) & (clay < 100))] =  8      # silt clay loam
    stype[where((clay >= 27) & (clay < 40.) & (sand >= 20) & (sand <= 45) & (clay < 100))] = 9      # clay loam
    stype[where((clay >= 35) & (sand > 45) & (clay < 100))] = 10     # sandy clay
    stype[where((clay >= 40) & (silt >= 40) & (clay < 100))] = 11     # silty clay
    stype[where((clay >= 40) & (sand <= 45) & (silt < 40) & (clay < 100))] = 12     # clay
    stype[where(stype == 0)] = 13
    return stype

def create_thres(stype,thres):
    from numpy import zeros, shape, arange, where
    ut = zeros(shape(stype))
    for i in arange(1,14):
        ut[where(stype == i)] = thres[int(i)-1]
    return ut

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='generate fv3 chem threshold friction velocities',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-d', '--data_directory',
                        default=None,
                        required=True,
                        help='path to the emission data (for single month: i.e. emi_C384/01)')
    parser.add_argument('-ut', '--threshold_velocity',
                        default="0.065,0.18,0.28,0.30,0.35,0.45,0.45,0.42,0.42,0.45,0.50,0.45,9999.0",
                        required=True,
                        help='Threshold friction Velocity for soil types.  Enter as string: "0.065,0.18,0.28,0.30,0.35,0.45,0.45,0.42,0.42,0.45,0.50,0.45,9999.0"')
    parser.add_argument('-r','--resolution',
                        default='C384',
                        help='FV3 Resolution: C384, C96, etc...')
    args = parser.parse_args()

    d = os.path.abspath(args.data_directory)
    ut = array(args.threshold_velocity.split(','),dtype=float)
#    utb = array(args.threshold_velocity_box.split(','),dtype=float)
    res = args.resolution
#    if args.latlon_box is not None:
#        lonmin,latmin,lonmax,latmax = array(args.latlon_box.split(','),dtype=float)

    for i in arange(1,7):
        tile = 'tile{}'.format(int(i))
        #form full path of files
        clay_file = os.path.join(d, tile, 'clay.dat')
        sand_file = os.path.join(d, tile, 'sand.dat')
        output = os.path.join(d, tile, 'uthr.dat')
        print('Creating threshold data for {}'.format(tile))
        # open clay and sand
        print('     Opening Clay...')
        clay = open_fv3_binary(clay_file, res=res, tile=i).clay
        print('     Opening Sand...')
        sand = open_fv3_binary(sand_file, res=res, tile=i).sand
        # calculate silt from sand and clay
        #( 1 = clay + sand + silt)
        silt = (1 - clay - sand).where( clay < 100)
        # needs % multiply by 100
        print('     Caclulating Soil Type...')
        stype = calc_soil_type(clay*100,sand*100,silt*100)
        st = clay.copy()
        st.data = stype
        print('     Setting Thresholds...')
        thres = create_thres(stype,ut)
        print('     Output: {}'.format(output))
        to_prepchem_binary(thres.T,fname=output)
        #to_prepchem_binary(st.T,fname=output)
